// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: castaneai/arena/v1/backend.proto

package arenav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/castaneai/arena/arenaconnect/castaneai/arena/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BackendServiceName is the fully-qualified name of the BackendService service.
	BackendServiceName = "castaneai.arena.v1.BackendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BackendServiceAddRoomGroupProcedure is the fully-qualified name of the BackendService's
	// AddContainer RPC.
	BackendServiceAddRoomGroupProcedure = "/castaneai.arena.v1.BackendService/AddContainer"
	// BackendServiceDeleteRoomGroupProcedure is the fully-qualified name of the BackendService's
	// DeleteContainer RPC.
	BackendServiceDeleteRoomGroupProcedure = "/castaneai.arena.v1.BackendService/DeleteContainer"
	// BackendServiceSetRoomResultProcedure is the fully-qualified name of the BackendService's
	// SetRoomResult RPC.
	BackendServiceSetRoomResultProcedure = "/castaneai.arena.v1.BackendService/SetRoomResult"
	// BackendServiceFreeRoomProcedure is the fully-qualified name of the BackendService's ReleaseRoom RPC.
	BackendServiceFreeRoomProcedure = "/castaneai.arena.v1.BackendService/ReleaseRoom"
)

// BackendServiceClient is a client for the castaneai.arena.v1.BackendService service.
type BackendServiceClient interface {
	AddRoomGroup(context.Context, *connect.Request[v1.AddRoomGroupRequest]) (*connect.ServerStreamForClient[v1.AddRoomGroupResponse], error)
	DeleteRoomGroup(context.Context, *connect.Request[v1.DeleteRoomGroupRequest]) (*connect.Response[v1.DeleteRoomGroupResponse], error)
	SetRoomResult(context.Context, *connect.Request[v1.SetRoomResultRequest]) (*connect.Response[v1.SetRoomResultResponse], error)
	FreeRoom(context.Context, *connect.Request[v1.FreeRoomRequest]) (*connect.Response[v1.FreeRoomResponse], error)
}

// NewBackendServiceClient constructs a client for the castaneai.arena.v1.BackendService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backendServiceMethods := v1.File_castaneai_arena_v1_backend_proto.Services().ByName("BackendService").Methods()
	return &backendServiceClient{
		addRoomGroup: connect.NewClient[v1.AddRoomGroupRequest, v1.AddRoomGroupResponse](
			httpClient,
			baseURL+BackendServiceAddRoomGroupProcedure,
			connect.WithSchema(backendServiceMethods.ByName("AddContainer")),
			connect.WithClientOptions(opts...),
		),
		deleteRoomGroup: connect.NewClient[v1.DeleteRoomGroupRequest, v1.DeleteRoomGroupResponse](
			httpClient,
			baseURL+BackendServiceDeleteRoomGroupProcedure,
			connect.WithSchema(backendServiceMethods.ByName("DeleteContainer")),
			connect.WithClientOptions(opts...),
		),
		setRoomResult: connect.NewClient[v1.SetRoomResultRequest, v1.SetRoomResultResponse](
			httpClient,
			baseURL+BackendServiceSetRoomResultProcedure,
			connect.WithSchema(backendServiceMethods.ByName("SetRoomResult")),
			connect.WithClientOptions(opts...),
		),
		freeRoom: connect.NewClient[v1.FreeRoomRequest, v1.FreeRoomResponse](
			httpClient,
			baseURL+BackendServiceFreeRoomProcedure,
			connect.WithSchema(backendServiceMethods.ByName("ReleaseRoom")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backendServiceClient implements BackendServiceClient.
type backendServiceClient struct {
	addRoomGroup    *connect.Client[v1.AddRoomGroupRequest, v1.AddRoomGroupResponse]
	deleteRoomGroup *connect.Client[v1.DeleteRoomGroupRequest, v1.DeleteRoomGroupResponse]
	setRoomResult   *connect.Client[v1.SetRoomResultRequest, v1.SetRoomResultResponse]
	freeRoom        *connect.Client[v1.FreeRoomRequest, v1.FreeRoomResponse]
}

// AddRoomGroup calls castaneai.arena.v1.BackendService.AddContainer.
func (c *backendServiceClient) AddRoomGroup(ctx context.Context, req *connect.Request[v1.AddRoomGroupRequest]) (*connect.ServerStreamForClient[v1.AddRoomGroupResponse], error) {
	return c.addRoomGroup.CallServerStream(ctx, req)
}

// DeleteRoomGroup calls castaneai.arena.v1.BackendService.DeleteContainer.
func (c *backendServiceClient) DeleteRoomGroup(ctx context.Context, req *connect.Request[v1.DeleteRoomGroupRequest]) (*connect.Response[v1.DeleteRoomGroupResponse], error) {
	return c.deleteRoomGroup.CallUnary(ctx, req)
}

// SetRoomResult calls castaneai.arena.v1.BackendService.SetRoomResult.
func (c *backendServiceClient) SetRoomResult(ctx context.Context, req *connect.Request[v1.SetRoomResultRequest]) (*connect.Response[v1.SetRoomResultResponse], error) {
	return c.setRoomResult.CallUnary(ctx, req)
}

// FreeRoom calls castaneai.arena.v1.BackendService.ReleaseRoom.
func (c *backendServiceClient) FreeRoom(ctx context.Context, req *connect.Request[v1.FreeRoomRequest]) (*connect.Response[v1.FreeRoomResponse], error) {
	return c.freeRoom.CallUnary(ctx, req)
}

// BackendServiceHandler is an implementation of the castaneai.arena.v1.BackendService service.
type BackendServiceHandler interface {
	AddRoomGroup(context.Context, *connect.Request[v1.AddRoomGroupRequest], *connect.ServerStream[v1.AddRoomGroupResponse]) error
	DeleteRoomGroup(context.Context, *connect.Request[v1.DeleteRoomGroupRequest]) (*connect.Response[v1.DeleteRoomGroupResponse], error)
	SetRoomResult(context.Context, *connect.Request[v1.SetRoomResultRequest]) (*connect.Response[v1.SetRoomResultResponse], error)
	FreeRoom(context.Context, *connect.Request[v1.FreeRoomRequest]) (*connect.Response[v1.FreeRoomResponse], error)
}

// NewBackendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackendServiceHandler(svc BackendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backendServiceMethods := v1.File_castaneai_arena_v1_backend_proto.Services().ByName("BackendService").Methods()
	backendServiceAddRoomGroupHandler := connect.NewServerStreamHandler(
		BackendServiceAddRoomGroupProcedure,
		svc.AddRoomGroup,
		connect.WithSchema(backendServiceMethods.ByName("AddContainer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceDeleteRoomGroupHandler := connect.NewUnaryHandler(
		BackendServiceDeleteRoomGroupProcedure,
		svc.DeleteRoomGroup,
		connect.WithSchema(backendServiceMethods.ByName("DeleteContainer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceSetRoomResultHandler := connect.NewUnaryHandler(
		BackendServiceSetRoomResultProcedure,
		svc.SetRoomResult,
		connect.WithSchema(backendServiceMethods.ByName("SetRoomResult")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceFreeRoomHandler := connect.NewUnaryHandler(
		BackendServiceFreeRoomProcedure,
		svc.FreeRoom,
		connect.WithSchema(backendServiceMethods.ByName("ReleaseRoom")),
		connect.WithHandlerOptions(opts...),
	)
	return "/castaneai.arena.v1.BackendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackendServiceAddRoomGroupProcedure:
			backendServiceAddRoomGroupHandler.ServeHTTP(w, r)
		case BackendServiceDeleteRoomGroupProcedure:
			backendServiceDeleteRoomGroupHandler.ServeHTTP(w, r)
		case BackendServiceSetRoomResultProcedure:
			backendServiceSetRoomResultHandler.ServeHTTP(w, r)
		case BackendServiceFreeRoomProcedure:
			backendServiceFreeRoomHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBackendServiceHandler struct{}

func (UnimplementedBackendServiceHandler) AddRoomGroup(context.Context, *connect.Request[v1.AddRoomGroupRequest], *connect.ServerStream[v1.AddRoomGroupResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("castaneai.arena.v1.BackendService.AddContainer is not implemented"))
}

func (UnimplementedBackendServiceHandler) DeleteRoomGroup(context.Context, *connect.Request[v1.DeleteRoomGroupRequest]) (*connect.Response[v1.DeleteRoomGroupResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("castaneai.arena.v1.BackendService.DeleteContainer is not implemented"))
}

func (UnimplementedBackendServiceHandler) SetRoomResult(context.Context, *connect.Request[v1.SetRoomResultRequest]) (*connect.Response[v1.SetRoomResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("castaneai.arena.v1.BackendService.SetRoomResult is not implemented"))
}

func (UnimplementedBackendServiceHandler) FreeRoom(context.Context, *connect.Request[v1.FreeRoomRequest]) (*connect.Response[v1.FreeRoomResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("castaneai.arena.v1.BackendService.ReleaseRoom is not implemented"))
}
