// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: castaneai/arena/v1/backend.proto

package arenav1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRoomGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	FleetName     string                 `protobuf:"bytes,2,opt,name=fleet_name,json=fleetName,proto3" json:"fleet_name,omitempty"`
	Capacity      uint32                 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoomGroupRequest) Reset() {
	*x = AddRoomGroupRequest{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoomGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomGroupRequest) ProtoMessage() {}

func (x *AddRoomGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomGroupRequest.ProtoReflect.Descriptor instead.
func (*AddRoomGroupRequest) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{0}
}

func (x *AddRoomGroupRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddRoomGroupRequest) GetFleetName() string {
	if x != nil {
		return x.FleetName
	}
	return ""
}

func (x *AddRoomGroupRequest) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type AddRoomGroupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RoomGroupEvent:
	//
	//	*AddRoomGroupResponse_RoomAllocated
	RoomGroupEvent isAddRoomGroupResponse_RoomGroupEvent `protobuf_oneof:"room_group_event"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddRoomGroupResponse) Reset() {
	*x = AddRoomGroupResponse{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoomGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoomGroupResponse) ProtoMessage() {}

func (x *AddRoomGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoomGroupResponse.ProtoReflect.Descriptor instead.
func (*AddRoomGroupResponse) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{1}
}

func (x *AddRoomGroupResponse) GetRoomGroupEvent() isAddRoomGroupResponse_RoomGroupEvent {
	if x != nil {
		return x.RoomGroupEvent
	}
	return nil
}

func (x *AddRoomGroupResponse) GetRoomAllocated() *RoomGroupEventRoomAllocated {
	if x != nil {
		if x, ok := x.RoomGroupEvent.(*AddRoomGroupResponse_RoomAllocated); ok {
			return x.RoomAllocated
		}
	}
	return nil
}

type isAddRoomGroupResponse_RoomGroupEvent interface {
	isAddRoomGroupResponse_RoomGroupEvent()
}

type AddRoomGroupResponse_RoomAllocated struct {
	RoomAllocated *RoomGroupEventRoomAllocated `protobuf:"bytes,1,opt,name=room_allocated,json=roomAllocated,proto3,oneof"`
}

func (*AddRoomGroupResponse_RoomAllocated) isAddRoomGroupResponse_RoomGroupEvent() {}

type RoomGroupEventRoomAllocated struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomInitialData []byte                 `protobuf:"bytes,2,opt,name=room_initial_data,json=roomInitialData,proto3" json:"room_initial_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RoomGroupEventRoomAllocated) Reset() {
	*x = RoomGroupEventRoomAllocated{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomGroupEventRoomAllocated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomGroupEventRoomAllocated) ProtoMessage() {}

func (x *RoomGroupEventRoomAllocated) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomGroupEventRoomAllocated.ProtoReflect.Descriptor instead.
func (*RoomGroupEventRoomAllocated) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{2}
}

func (x *RoomGroupEventRoomAllocated) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomGroupEventRoomAllocated) GetRoomInitialData() []byte {
	if x != nil {
		return x.RoomInitialData
	}
	return nil
}

type DeleteRoomGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	FleetName     string                 `protobuf:"bytes,2,opt,name=fleet_name,json=fleetName,proto3" json:"fleet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomGroupRequest) Reset() {
	*x = DeleteRoomGroupRequest{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomGroupRequest) ProtoMessage() {}

func (x *DeleteRoomGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoomGroupRequest) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRoomGroupRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DeleteRoomGroupRequest) GetFleetName() string {
	if x != nil {
		return x.FleetName
	}
	return ""
}

type DeleteRoomGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomGroupResponse) Reset() {
	*x = DeleteRoomGroupResponse{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomGroupResponse) ProtoMessage() {}

func (x *DeleteRoomGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomGroupResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoomGroupResponse) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{4}
}

type SetRoomResultRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RoomId               string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomResultData       []byte                 `protobuf:"bytes,2,opt,name=room_result_data,json=roomResultData,proto3" json:"room_result_data,omitempty"`
	ResultDataTtlSeconds uint32                 `protobuf:"varint,3,opt,name=result_data_ttl_seconds,json=resultDataTtlSeconds,proto3" json:"result_data_ttl_seconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SetRoomResultRequest) Reset() {
	*x = SetRoomResultRequest{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoomResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomResultRequest) ProtoMessage() {}

func (x *SetRoomResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomResultRequest.ProtoReflect.Descriptor instead.
func (*SetRoomResultRequest) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{5}
}

func (x *SetRoomResultRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SetRoomResultRequest) GetRoomResultData() []byte {
	if x != nil {
		return x.RoomResultData
	}
	return nil
}

func (x *SetRoomResultRequest) GetResultDataTtlSeconds() uint32 {
	if x != nil {
		return x.ResultDataTtlSeconds
	}
	return 0
}

type SetRoomResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRoomResultResponse) Reset() {
	*x = SetRoomResultResponse{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRoomResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoomResultResponse) ProtoMessage() {}

func (x *SetRoomResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoomResultResponse.ProtoReflect.Descriptor instead.
func (*SetRoomResultResponse) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{6}
}

type FreeRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	FleetName     string                 `protobuf:"bytes,2,opt,name=fleet_name,json=fleetName,proto3" json:"fleet_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeRoomRequest) Reset() {
	*x = FreeRoomRequest{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeRoomRequest) ProtoMessage() {}

func (x *FreeRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeRoomRequest.ProtoReflect.Descriptor instead.
func (*FreeRoomRequest) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{7}
}

func (x *FreeRoomRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FreeRoomRequest) GetFleetName() string {
	if x != nil {
		return x.FleetName
	}
	return ""
}

type FreeRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreeRoomResponse) Reset() {
	*x = FreeRoomResponse{}
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreeRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreeRoomResponse) ProtoMessage() {}

func (x *FreeRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreeRoomResponse.ProtoReflect.Descriptor instead.
func (*FreeRoomResponse) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_backend_proto_rawDescGZIP(), []int{8}
}

var File_castaneai_arena_v1_backend_proto protoreflect.FileDescriptor

const file_castaneai_arena_v1_backend_proto_rawDesc = "" +
	"\n" +
	" castaneai/arena/v1/backend.proto\x12\x12castaneai.arena.v1\x1a\x1bbuf/validate/validate.proto\"\x82\x01\n" +
	"\x13AddRoomGroupRequest\x12 \n" +
	"\aaddress\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aaddress\x12%\n" +
	"\n" +
	"fleet_name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tfleetName\x12\"\n" +
	"\bcapacity\x18\x03 \x01(\rB\x06\xbaH\x03\xc8\x01\x01R\bcapacity\"\x84\x01\n" +
	"\x14AddRoomGroupResponse\x12X\n" +
	"\x0eroom_allocated\x18\x01 \x01(\v2/.castaneai.arena.v1.RoomGroupEventRoomAllocatedH\x00R\rroomAllocatedB\x12\n" +
	"\x10room_group_event\"j\n" +
	"\x1bRoomGroupEventRoomAllocated\x12\x1f\n" +
	"\aroom_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06roomId\x12*\n" +
	"\x11room_initial_data\x18\x02 \x01(\fR\x0froomInitialData\"a\n" +
	"\x16DeleteRoomGroupRequest\x12 \n" +
	"\aaddress\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aaddress\x12%\n" +
	"\n" +
	"fleet_name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tfleetName\"\x19\n" +
	"\x17DeleteRoomGroupResponse\"\xa9\x01\n" +
	"\x14SetRoomResultRequest\x12\x1f\n" +
	"\aroom_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06roomId\x120\n" +
	"\x10room_result_data\x18\x02 \x01(\fB\x06\xbaH\x03\xc8\x01\x01R\x0eroomResultData\x12>\n" +
	"\x17result_data_ttl_seconds\x18\x03 \x01(\rB\a\xbaH\x04*\x02 \x00R\x14resultDataTtlSeconds\"\x17\n" +
	"\x15SetRoomResultResponse\"Z\n" +
	"\x0fFreeRoomRequest\x12 \n" +
	"\aaddress\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aaddress\x12%\n" +
	"\n" +
	"fleet_name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tfleetName\"\x12\n" +
	"\x10FreeRoomResponse2\x9e\x03\n" +
	"\x0eBackendService\x12c\n" +
	"\fAddRoomGroup\x12'.castaneai.arena.v1.AddRoomGroupRequest\x1a(.castaneai.arena.v1.AddRoomGroupResponse0\x01\x12j\n" +
	"\x0fDeleteRoomGroup\x12*.castaneai.arena.v1.DeleteRoomGroupRequest\x1a+.castaneai.arena.v1.DeleteRoomGroupResponse\x12d\n" +
	"\rSetRoomResult\x12(.castaneai.arena.v1.SetRoomResultRequest\x1a).castaneai.arena.v1.SetRoomResultResponse\x12U\n" +
	"\bFreeRoom\x12#.castaneai.arena.v1.FreeRoomRequest\x1a$.castaneai.arena.v1.FreeRoomResponseB\xd4\x01\n" +
	"\x16com.castaneai.arena.v1B\fBackendProtoP\x01ZBgithub.com/castaneai/arena/arenaconnect/castaneai/arena/v1;arenav1\xa2\x02\x03CAX\xaa\x02\x12Castaneai.Arena.V1\xca\x02\x12Castaneai\\Arena\\V1\xe2\x02\x1eCastaneai\\Arena\\V1\\GPBMetadata\xea\x02\x14Castaneai::Arena::V1b\x06proto3"

var (
	file_castaneai_arena_v1_backend_proto_rawDescOnce sync.Once
	file_castaneai_arena_v1_backend_proto_rawDescData []byte
)

func file_castaneai_arena_v1_backend_proto_rawDescGZIP() []byte {
	file_castaneai_arena_v1_backend_proto_rawDescOnce.Do(func() {
		file_castaneai_arena_v1_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_castaneai_arena_v1_backend_proto_rawDesc), len(file_castaneai_arena_v1_backend_proto_rawDesc)))
	})
	return file_castaneai_arena_v1_backend_proto_rawDescData
}

var file_castaneai_arena_v1_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_castaneai_arena_v1_backend_proto_goTypes = []any{
	(*AddRoomGroupRequest)(nil),         // 0: castaneai.arena.v1.AddRoomGroupRequest
	(*AddRoomGroupResponse)(nil),        // 1: castaneai.arena.v1.AddRoomGroupResponse
	(*RoomGroupEventRoomAllocated)(nil), // 2: castaneai.arena.v1.RoomGroupEventRoomAllocated
	(*DeleteRoomGroupRequest)(nil),      // 3: castaneai.arena.v1.DeleteRoomGroupRequest
	(*DeleteRoomGroupResponse)(nil),     // 4: castaneai.arena.v1.DeleteRoomGroupResponse
	(*SetRoomResultRequest)(nil),        // 5: castaneai.arena.v1.SetRoomResultRequest
	(*SetRoomResultResponse)(nil),       // 6: castaneai.arena.v1.SetRoomResultResponse
	(*FreeRoomRequest)(nil),             // 7: castaneai.arena.v1.FreeRoomRequest
	(*FreeRoomResponse)(nil),            // 8: castaneai.arena.v1.FreeRoomResponse
}
var file_castaneai_arena_v1_backend_proto_depIdxs = []int32{
	2, // 0: castaneai.arena.v1.AddRoomGroupResponse.room_allocated:type_name -> castaneai.arena.v1.RoomGroupEventRoomAllocated
	0, // 1: castaneai.arena.v1.BackendService.NewContainer:input_type -> castaneai.arena.v1.AddRoomGroupRequest
	3, // 2: castaneai.arena.v1.BackendService.DeleteContainer:input_type -> castaneai.arena.v1.DeleteRoomGroupRequest
	5, // 3: castaneai.arena.v1.BackendService.SetRoomResult:input_type -> castaneai.arena.v1.SetRoomResultRequest
	7, // 4: castaneai.arena.v1.BackendService.FreeRoom:input_type -> castaneai.arena.v1.FreeRoomRequest
	1, // 5: castaneai.arena.v1.BackendService.NewContainer:output_type -> castaneai.arena.v1.AddRoomGroupResponse
	4, // 6: castaneai.arena.v1.BackendService.DeleteContainer:output_type -> castaneai.arena.v1.DeleteRoomGroupResponse
	6, // 7: castaneai.arena.v1.BackendService.SetRoomResult:output_type -> castaneai.arena.v1.SetRoomResultResponse
	8, // 8: castaneai.arena.v1.BackendService.FreeRoom:output_type -> castaneai.arena.v1.FreeRoomResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_castaneai_arena_v1_backend_proto_init() }
func file_castaneai_arena_v1_backend_proto_init() {
	if File_castaneai_arena_v1_backend_proto != nil {
		return
	}
	file_castaneai_arena_v1_backend_proto_msgTypes[1].OneofWrappers = []any{
		(*AddRoomGroupResponse_RoomAllocated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_castaneai_arena_v1_backend_proto_rawDesc), len(file_castaneai_arena_v1_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_castaneai_arena_v1_backend_proto_goTypes,
		DependencyIndexes: file_castaneai_arena_v1_backend_proto_depIdxs,
		MessageInfos:      file_castaneai_arena_v1_backend_proto_msgTypes,
	}.Build()
	File_castaneai_arena_v1_backend_proto = out.File
	file_castaneai_arena_v1_backend_proto_goTypes = nil
	file_castaneai_arena_v1_backend_proto_depIdxs = nil
}
