// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: castaneai/arena/v1/frontend.proto

package arenav1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRoomRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	FleetName       string                 `protobuf:"bytes,2,opt,name=fleet_name,json=fleetName,proto3" json:"fleet_name,omitempty"`
	RoomInitialData []byte                 `protobuf:"bytes,3,opt,name=room_initial_data,json=roomInitialData,proto3" json:"room_initial_data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AllocateRoomRequest) Reset() {
	*x = AllocateRoomRequest{}
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRoomRequest) ProtoMessage() {}

func (x *AllocateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRoomRequest.ProtoReflect.Descriptor instead.
func (*AllocateRoomRequest) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AllocateRoomRequest) GetFleetName() string {
	if x != nil {
		return x.FleetName
	}
	return ""
}

func (x *AllocateRoomRequest) GetRoomInitialData() []byte {
	if x != nil {
		return x.RoomInitialData
	}
	return nil
}

type AllocateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRoomResponse) Reset() {
	*x = AllocateRoomResponse{}
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRoomResponse) ProtoMessage() {}

func (x *AllocateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRoomResponse.ProtoReflect.Descriptor instead.
func (*AllocateRoomResponse) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_frontend_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AllocateRoomResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetRoomResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResultRequest) Reset() {
	*x = GetRoomResultRequest{}
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResultRequest) ProtoMessage() {}

func (x *GetRoomResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResultRequest.ProtoReflect.Descriptor instead.
func (*GetRoomResultRequest) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomResultRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type GetRoomResultResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomId         string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	RoomResultData []byte                 `protobuf:"bytes,2,opt,name=room_result_data,json=roomResultData,proto3" json:"room_result_data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRoomResultResponse) Reset() {
	*x = GetRoomResultResponse{}
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResultResponse) ProtoMessage() {}

func (x *GetRoomResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castaneai_arena_v1_frontend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResultResponse.ProtoReflect.Descriptor instead.
func (*GetRoomResultResponse) Descriptor() ([]byte, []int) {
	return file_castaneai_arena_v1_frontend_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomResultResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *GetRoomResultResponse) GetRoomResultData() []byte {
	if x != nil {
		return x.RoomResultData
	}
	return nil
}

var File_castaneai_arena_v1_frontend_proto protoreflect.FileDescriptor

const file_castaneai_arena_v1_frontend_proto_rawDesc = "" +
	"\n" +
	"!castaneai/arena/v1/frontend.proto\x12\x12castaneai.arena.v1\x1a\x1bbuf/validate/validate.proto\"\x89\x01\n" +
	"\x13AllocateRoomRequest\x12\x1f\n" +
	"\aroom_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06roomId\x12%\n" +
	"\n" +
	"fleet_name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\tfleetName\x12*\n" +
	"\x11room_initial_data\x18\x03 \x01(\fR\x0froomInitialData\"Y\n" +
	"\x14AllocateRoomResponse\x12\x1f\n" +
	"\aroom_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06roomId\x12 \n" +
	"\aaddress\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\aaddress\"7\n" +
	"\x14GetRoomResultRequest\x12\x1f\n" +
	"\aroom_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06roomId\"b\n" +
	"\x15GetRoomResultResponse\x12\x1f\n" +
	"\aroom_id\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x06roomId\x12(\n" +
	"\x10room_result_data\x18\x02 \x01(\fR\x0eroomResultData2\xda\x01\n" +
	"\x0fFrontendService\x12a\n" +
	"\fAllocateRoom\x12'.castaneai.arena.v1.AllocateRoomRequest\x1a(.castaneai.arena.v1.AllocateRoomResponse\x12d\n" +
	"\rGetRoomResult\x12(.castaneai.arena.v1.GetRoomResultRequest\x1a).castaneai.arena.v1.GetRoomResultResponseB\xd5\x01\n" +
	"\x16com.castaneai.arena.v1B\rFrontendProtoP\x01ZBgithub.com/castaneai/arena/arenaconnect/castaneai/arena/v1;arenav1\xa2\x02\x03CAX\xaa\x02\x12Castaneai.Arena.V1\xca\x02\x12Castaneai\\Arena\\V1\xe2\x02\x1eCastaneai\\Arena\\V1\\GPBMetadata\xea\x02\x14Castaneai::Arena::V1b\x06proto3"

var (
	file_castaneai_arena_v1_frontend_proto_rawDescOnce sync.Once
	file_castaneai_arena_v1_frontend_proto_rawDescData []byte
)

func file_castaneai_arena_v1_frontend_proto_rawDescGZIP() []byte {
	file_castaneai_arena_v1_frontend_proto_rawDescOnce.Do(func() {
		file_castaneai_arena_v1_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_castaneai_arena_v1_frontend_proto_rawDesc), len(file_castaneai_arena_v1_frontend_proto_rawDesc)))
	})
	return file_castaneai_arena_v1_frontend_proto_rawDescData
}

var file_castaneai_arena_v1_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_castaneai_arena_v1_frontend_proto_goTypes = []any{
	(*AllocateRoomRequest)(nil),   // 0: castaneai.arena.v1.AllocateRoomRequest
	(*AllocateRoomResponse)(nil),  // 1: castaneai.arena.v1.AllocateRoomResponse
	(*GetRoomResultRequest)(nil),  // 2: castaneai.arena.v1.GetRoomResultRequest
	(*GetRoomResultResponse)(nil), // 3: castaneai.arena.v1.GetRoomResultResponse
}
var file_castaneai_arena_v1_frontend_proto_depIdxs = []int32{
	0, // 0: castaneai.arena.v1.FrontendService.AllocateRoom:input_type -> castaneai.arena.v1.AllocateRoomRequest
	2, // 1: castaneai.arena.v1.FrontendService.GetRoomResult:input_type -> castaneai.arena.v1.GetRoomResultRequest
	1, // 2: castaneai.arena.v1.FrontendService.AllocateRoom:output_type -> castaneai.arena.v1.AllocateRoomResponse
	3, // 3: castaneai.arena.v1.FrontendService.GetRoomResult:output_type -> castaneai.arena.v1.GetRoomResultResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_castaneai_arena_v1_frontend_proto_init() }
func file_castaneai_arena_v1_frontend_proto_init() {
	if File_castaneai_arena_v1_frontend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_castaneai_arena_v1_frontend_proto_rawDesc), len(file_castaneai_arena_v1_frontend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_castaneai_arena_v1_frontend_proto_goTypes,
		DependencyIndexes: file_castaneai_arena_v1_frontend_proto_depIdxs,
		MessageInfos:      file_castaneai_arena_v1_frontend_proto_msgTypes,
	}.Build()
	File_castaneai_arena_v1_frontend_proto = out.File
	file_castaneai_arena_v1_frontend_proto_goTypes = nil
	file_castaneai_arena_v1_frontend_proto_depIdxs = nil
}
